apiVersion: v1
kind: Service
metadata:
  labels:
    app: "zuul-api-gateway"
  name: "zuul-api-gateway"
spec:
  selector:
    app: "zuul-api-gateway"
  ports:
  - name: "http"
    port: 9999
    targetPort: 9999
    nodePort: 32470
  type: NodePort

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zuul-api-gateway"
spec:
  selector:
    matchLabels:
      app: "zuul-api-gateway"
  template:
    metadata:
      labels:
        app: "zuul-api-gateway"
    spec:
      containers:
      - name: "zuul-api-gateway"
        image:  "deekshithsn/zuul"
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 9999
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - react-ui
            topologyKey: "kubernetes.io/hostname"
