apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
  labels:
    {{-  include "ui-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ui-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ui-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.container.containerPort }}
