apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "zuul-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{-  include "zuul-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zuul-helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image:  {{ .Values.image.repository | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.containerPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        
      
        
