apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "zuul-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "zuul-helm.selectorLabels" . | nindent 4 }}
